---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/rootfs

inputs:
  - name: pcf-azure-infrastructure
  - name: terraform-infra-state

outputs:
  - name: terraform-infra-state-output

run:
  path: pcf-azure-infrastructure/tasks/provision-infra/task.sh

params:
  AZURE_SUBSCRIPTION_ID:
  AZURE_TENANT_ID:
  AZURE_CLIENT_ID:
  AZURE_CLIENT_SECRET:
  AZURE_REGION:
  AZURE_TERRAFORM_PREFIX:


  AZURE_VM_ADMIN:
  PCF_ERT_DOMAIN:
  PCF_SSH_KEY_PUB:
  AZURE_MULTI_RESGROUP_NETWORK:
  AZURE_MULTI_RESGROUP_PCF:
  AZURE_MULTI_RESGROUP_INFRA_SUBNET_NAME:
  AZURE_MULTI_RESGROUP_INFRA_VNET_NAME:
  AZURE_ACCOUNT_NAME:
  AZURE_BUILDPACKS_CONTAINER:
  AZURE_DROPLETS_CONTAINER:
  AZURE_PACKAGES_CONTAINER:
  AZURE_RESOURCES_CONTAINER:
  AZURE_TERRAFORM_VNET_CIDR:
  AZURE_TERRAFORM_SUBNET_INFRA_CIDR:
  AZURE_TERRAFORM_SUBNET_ERT_CIDR:
  AZURE_TERRAFORM_SUBNET_SERVICES1_CIDR:
  AZURE_TERRAFORM_SUBNET_DYNAMIC_SERVICES_CIDR:
  PCF_OPSMAN_DISK_SIZE_IN_GB:
