---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/rootfs

inputs:
  - name: pcf-azure-infrastructure
  - name: terraform-infra-state

outputs:
  - name: terraform-infra-state-output

run:
  path: pcf-azure-infrastructure/tasks/provision-infra/task.sh

params:
  AZURE_SUBSCRIPTION_ID:
  AZURE_TENANT_ID:
  AZURE_CLIENT_ID:
  AZURE_CLIENT_SECRET:
  AZURE_REGION:
  AZURE_MULTI_RESGROUP_NETWORK:
  AZURE_MULTI_RESGROUP_PCF:
  AZURE_TERRAFORM_VNET_NAME:
  AZURE_TERRAFORM_VNET_CIDR:
  AZURE_TERRAFORM_SUBNET_INFRA_NAME:
  AZURE_TERRAFORM_SUBNET_INFRA_CIDR:
  AZURE_TERRAFORM_SUBNET_ERT_NAME:
  AZURE_TERRAFORM_SUBNET_ERT_CIDR:
  AZURE_TERRAFORM_SUBNET_SERVICES1_NAME:
  AZURE_TERRAFORM_SUBNET_SERVICES1_CIDR:
  AZURE_TERRAFORM_SUBNET_DYNAMIC_SERVICES_NAME:
  AZURE_TERRAFORM_SUBNET_DYNAMIC_SERVICES_CIDR:
  AZURE_PCF_TERRAFORM_STORAGE_ACCOUNT_NAME:
  AZURE_PCF_TERRAFORM_CONTAINER_NAME: